# Generated by Django 3.2.8 on 2021-10-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user_id',
        ),
    ]
